run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

  disable:
    - structcheck
    - varcheck
    - deadcode
    - golint
    - interfacer
    - maligned
    - scopelint

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

  govet:
    check-shadowing: false

  gofmt:
    simplify: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
